# Worlds listed here will be ignored by the plugin
ignored-worlds:
- creative

# Should items be dropped on normal leaf decay
drop-on-decay: false

# Regular apple drop chance (between 0 and 1)
apple-chance: 0.05

# Golden apple drop chance (between 0 and 1)
golden-apple-chance: 0.05

# Cocoa drop chance (between 0 and 1)
cocoa-chance: 0.02

# Leaf drop chance (between 0 and 1)
leaf-chance: 0.05
